import type {
  Bom,
  BreakdownTicket,
  ClientFollowUp,
  ClientInteraction,
  Dispatch,
  Employee,
  Expense,
  Invoice,
  LedgerEntry,
  Machine,
  Material,
  Order,
  Party,
  PlantNotice,
  Product,
  ProductionEntry,
  PurchaseOrder,
  QcInspection,
  StockMovement,
  WorkOrder,
} from "./types";

const today = new Date().toISOString().slice(0, 10);
const addDays = (days: number) => new Date(Date.now() + days * 86_400_000).toISOString().slice(0, 10);

export const initialMaterials: Material[] = [
  {
    id: "m-polypropylene",
    code: "RM-PP-01",
    name: "Virgin Polypropylene Granules (Grade H110)",
    category: "Raw Material",
    unit: "kg",
    currentStock: 1420,
    lowStockThreshold: 500,
    unitCost: 112,
  },
  {
    id: "m-masterbatch",
    code: "MB-BLU-02",
    name: "Industrial Blue Masterbatch (Pigment)",
    category: "Color / Additive",
    unit: "kg",
    currentStock: 45,
    lowStockThreshold: 60,
    unitCost: 280,
  },
  {
    id: "m-labels",
    code: "PKG-LBL-03",
    name: "Barcoded Brand Labels (Roll)",
    category: "Packaging",
    unit: "pcs",
    currentStock: 3200,
    lowStockThreshold: 1500,
    unitCost: 1.5,
  },
  {
    id: "m-cartons",
    code: "PKG-BOX-04",
    name: "5-Ply Corrugated Heavy Dispatch Boxes",
    category: "Packaging",
    unit: "pcs",
    currentStock: 180,
    lowStockThreshold: 200,
    unitCost: 45,
  },
  {
    id: "m-stretchfilm",
    code: "PKG-STR-05",
    name: "Pallet Wrap Stretch Film (23 Micron)",
    category: "Packaging",
    unit: "rolls",
    currentStock: 32,
    lowStockThreshold: 20,
    unitCost: 350,
  },
];

export const initialProducts: Product[] = [
  {
    id: "p-crate",
    code: "FG-CRT-20L",
    name: "20L Heavy Duty Industrial Storage Crate",
    category: "Storage Crates",
    unit: "pcs",
    dailyTarget: 400,
    currentFinishedStock: 285,
    sellingPrice: 320,
  },
  {
    id: "p-bin",
    code: "FG-BIN-45L",
    name: "45L Commercial Utility Pedal Dustbin",
    category: "Waste Management",
    unit: "pcs",
    dailyTarget: 250,
    currentFinishedStock: 140,
    sellingPrice: 480,
  },
  {
    id: "p-tray",
    code: "FG-TRY-IND",
    name: "Modular Industrial Parts Sorting Tray",
    category: "Component Trays",
    unit: "pcs",
    dailyTarget: 500,
    currentFinishedStock: 620,
    sellingPrice: 110,
  },
];

export const initialBoms: Bom[] = [
  {
    id: "b-crate-v2",
    productId: "p-crate",
    version: 2,
    isActive: true,
    createdAt: `${today}T08:15:00.000Z`,
    lineItems: [
      { materialId: "m-polypropylene", qtyPerUnit: 0.82 },
      { materialId: "m-masterbatch", qtyPerUnit: 0.018 },
      { materialId: "m-labels", qtyPerUnit: 1 },
      { materialId: "m-cartons", qtyPerUnit: 0.05 },
    ],
  },
  {
    id: "b-bin-v1",
    productId: "p-bin",
    version: 1,
    isActive: true,
    createdAt: `${today}T08:20:00.000Z`,
    lineItems: [
      { materialId: "m-polypropylene", qtyPerUnit: 1.15 },
      { materialId: "m-masterbatch", qtyPerUnit: 0.021 },
      { materialId: "m-labels", qtyPerUnit: 1 },
      { materialId: "m-cartons", qtyPerUnit: 0.08 },
    ],
  },
  {
    id: "b-tray-v1",
    productId: "p-tray",
    version: 1,
    isActive: true,
    createdAt: `${today}T08:25:00.000Z`,
    lineItems: [
      { materialId: "m-polypropylene", qtyPerUnit: 0.34 },
      { materialId: "m-masterbatch", qtyPerUnit: 0.009 },
      { materialId: "m-labels", qtyPerUnit: 1 },
    ],
  },
];

export const initialMachines: Machine[] = [
  {
    id: "mch-01",
    code: "IMM-250T-01",
    name: "L&T Injection Molding Machine #01 (250 Ton)",
    status: "Running",
    currentJob: "20L Storage Crate (WO-26-401)",
    operator: "Ramesh Sharma",
    runtimeHours: 4120,
    nextMaintenanceDate: addDays(5),
  },
  {
    id: "mch-02",
    code: "IMM-180T-02",
    name: "Windsor Injection Molding Machine #02 (180 Ton)",
    status: "Breakdown",
    currentJob: "Modular Parts Tray (WO-26-402)",
    operator: "Suresh Kumar",
    runtimeHours: 3850,
    nextMaintenanceDate: addDays(-2),
    lastBreakdownReason: "Hydraulic pump oil leak & pressure drop",
  },
  {
    id: "mch-03",
    code: "IMM-350T-03",
    name: "Toshiba Precision Molding Machine #03 (350 Ton)",
    status: "Idle",
    currentJob: "None (Tooling Changeover)",
    operator: "Vikram Singh",
    runtimeHours: 2100,
    nextMaintenanceDate: addDays(12),
  },
  {
    id: "mch-04",
    code: "CRUSH-15HP-04",
    name: "Heavy Duty Plastic Granulator & Crusher #04",
    status: "Maintenance",
    currentJob: "Preventive Maintenance (Blade Sharpening)",
    operator: "Maintenance Staff",
    runtimeHours: 5400,
    nextMaintenanceDate: today,
  },
];

export const initialBreakdownTickets: BreakdownTicket[] = [
  {
    id: "brk-101",
    machineId: "mch-02",
    symptom: "Hydraulic pressure loss below 120 bar during clamping cycle",
    severity: "Urgent",
    reportedBy: "Suresh Kumar (Operator)",
    stoppedTime: `${today}T11:15:00.000Z`,
    status: "In Repair",
  },
];

export const initialWorkOrders: WorkOrder[] = [
  {
    id: "wo-401",
    workOrderNumber: "WO-26-401",
    orderNumber: "WO-26-401",
    productId: "p-crate",
    quantityOrdered: 1000,
    quantity: 1000,
    quantityCompleted: 640,
    status: "In Progress",
    dueDate: addDays(2),
    assignedMachineId: "mch-01",
    assignedOperator: "Ramesh Sharma",
    materialReadiness: "Ready",
    stage: "Injection Molding",
    priority: "High",
    createdAt: `${addDays(-2)}T09:00:00.000Z`,
  },
  {
    id: "wo-402",
    workOrderNumber: "WO-26-402",
    orderNumber: "WO-26-402",
    productId: "p-tray",
    quantityOrdered: 800,
    quantity: 800,
    quantityCompleted: 320,
    status: "On Hold",
    dueDate: today,
    assignedMachineId: "mch-02",
    assignedOperator: "Suresh Kumar",
    materialReadiness: "Shortage Risk",
    stage: "Trimming & QC",
    priority: "Normal",
    createdAt: `${addDays(-3)}T10:30:00.000Z`,
  },
  {
    id: "wo-403",
    workOrderNumber: "WO-26-403",
    orderNumber: "WO-26-403",
    productId: "p-bin",
    quantityOrdered: 500,
    quantity: 500,
    quantityCompleted: 0,
    status: "Released",
    dueDate: addDays(5),
    assignedMachineId: "mch-03",
    assignedOperator: "Vikram Singh",
    materialReadiness: "Ready",
    stage: "Tooling Setup",
    priority: "Urgent",
    createdAt: `${today}T08:00:00.000Z`,
  },
];

export const initialQcInspections: QcInspection[] = [
  {
    id: "qc-301",
    batchNumber: "BATCH-26-09A",
    productId: "p-crate",
    inspectedQuantity: 240,
    inspectedQty: 240,
    passedQuantity: 234,
    passedQty: 234,
    rejectedQuantity: 6,
    rejectedQty: 6,
    defectCode: "DEF-01: Warping & Shrinkage",
    status: "Passed",
    inspector: "Amit Verma (QC Inspector)",
    date: today,
    inspectedAt: `${today}T09:30:00.000Z`,
    notes: "Dimensional check within ISO tolerance (+/- 0.5mm).",
  },
  {
    id: "qc-302",
    batchNumber: "BATCH-26-09B",
    productId: "p-tray",
    inspectedQuantity: 150,
    inspectedQty: 150,
    passedQuantity: 120,
    passedQty: 120,
    rejectedQuantity: 30,
    rejectedQty: 30,
    defectCode: "DEF-04: Color Streak & Burn Marks",
    status: "On Hold",
    inspector: "Amit Verma (QC Inspector)",
    date: today,
    inspectedAt: `${today}T11:00:00.000Z`,
    notes: "Hold placed due to masterbatch dispersion streak. Awaiting Disposition.",
  },
];

export const initialProductionEntries: ProductionEntry[] = [
  {
    id: "pe-101",
    productId: "p-crate",
    bomId: "b-crate-v2",
    quantityProduced: 240,
    quantityRejected: 6,
    rejectReason: "Warping due to cooling water pressure drop",
    shift: "Morning (08:00 - 16:00)",
    machineId: "Injection Molding Machine #01 (L&T 250T)",
    downtimeMinutes: 20,
    downtimeReason: "Mould nozzle de-clogging and heater band check",
    entryDate: today,
    enteredBy: "Ramesh Sharma (Shift Supervisor)",
    createdAt: `${today}T11:30:00.000Z`,
  },
  {
    id: "pe-102",
    productId: "p-tray",
    bomId: "b-tray-v1",
    quantityProduced: 320,
    quantityRejected: 4,
    rejectReason: "Side flash trimming defect",
    shift: "Morning (08:00 - 16:00)",
    machineId: "Injection Molding Machine #02 (Windsor 180T)",
    downtimeMinutes: 0,
    downtimeReason: "None - smooth run",
    entryDate: today,
    enteredBy: "Ramesh Sharma (Shift Supervisor)",
    createdAt: `${today}T13:45:00.000Z`,
  },
];

export const initialStockMovements: StockMovement[] = [
  {
    id: "sm-01",
    materialId: "m-polypropylene",
    type: "in",
    quantity: 1000,
    note: "PO-26-8801 Inward from Reliance Polymers",
    createdBy: "Inventory Head",
    createdAt: `${today}T07:30:00.000Z`,
  },
  {
    id: "sm-02",
    materialId: "m-polypropylene",
    type: "production_deduction",
    quantity: 196.8,
    referenceId: "pe-101",
    note: "Auto-deducted for 240 pcs 20L Crate",
    createdBy: "System Engine",
    createdAt: `${today}T11:30:00.000Z`,
  },
  {
    id: "sm-03",
    materialId: "m-masterbatch",
    type: "production_deduction",
    quantity: 4.32,
    referenceId: "pe-101",
    note: "Auto-deducted for 240 pcs 20L Crate",
    createdBy: "System Engine",
    createdAt: `${today}T11:30:00.000Z`,
  },
];

export const initialParties: Party[] = [
  {
    id: "party-jaipur-mart",
    name: "Jaipur Mega Mart & Distribution Ltd",
    type: "Customer",
    clientCategory: "dealer",
    phone: "9829012345",
    whatsapp: "9829012345",
    city: "Jaipur",
    gstin: "08AABCJ1020A1Z5",
    tags: ["VIP", "High Volume", "Dealer"],
    creditLimit: 350000,
    creditPeriodDays: 21,
    status: "active",
    notes: "Main distributor for Jaipur region. Demands palletized delivery.",
    lastOrderDate: addDays(-2),
    lastPaymentDate: addDays(-14),
  },
  {
    id: "party-arihant",
    name: "Arihant Industrial Supplies Corp",
    type: "Customer",
    clientCategory: "retailer",
    phone: "9829988776",
    whatsapp: "9829988776",
    city: "Jodhpur",
    gstin: "08AAJFA4432F1Z8",
    tags: ["Overdue Risk", "Retailer"],
    creditLimit: 30000,
    creditPeriodDays: 15,
    status: "dormant",
    notes: "No orders for over 45 days. Follow up for pending invoice payment.",
    lastOrderDate: addDays(-45),
    lastPaymentDate: addDays(-60),
  },
  {
    id: "party-marwar-plastics",
    name: "Marwar Plastic Agencies",
    type: "Customer",
    clientCategory: "dealer",
    phone: "9784112233",
    whatsapp: "9784112233",
    city: "Kota",
    gstin: "08BCCPR1234D1Z2",
    tags: ["New Lead", "Dealer"],
    creditLimit: 150000,
    creditPeriodDays: 14,
    status: "lead",
    notes: "Inquired about 45L Dustbins and 20L Crates.",
    lastOrderDate: "",
    lastPaymentDate: "",
  },
  {
    id: "party-reliance",
    name: "Reliance Polymers Raw Material Agency",
    type: "Supplier",
    clientCategory: "direct",
    phone: "9811223344",
    city: "Vadodara",
    gstin: "24AABCR2401G1Z3",
    tags: ["Raw Material", "Polymer"],
    creditLimit: 500000,
    creditPeriodDays: 30,
    status: "active",
    notes: "Primary supplier of virgin polypropylene granules.",
    lastOrderDate: addDays(-5),
    lastPaymentDate: addDays(-5),
  },
  {
    id: "party-shakti",
    name: "Shakti Corrugators & Packaging Hub",
    type: "Supplier",
    clientCategory: "direct",
    phone: "9828776655",
    city: "Jaipur",
    gstin: "08BBDPS4412K1Z2",
    tags: ["Packaging", "Boxes"],
    creditLimit: 120000,
    creditPeriodDays: 14,
    status: "active",
    notes: "Supplier of 5-ply corrugated dispatch boxes.",
    lastOrderDate: addDays(-8),
    lastPaymentDate: addDays(-12),
  },
];

export const initialInteractions: ClientInteraction[] = [
  {
    id: "int-101",
    clientId: "party-jaipur-mart",
    type: "whatsapp",
    text: "Sent dispatch confirmation and invoice INV-26-1001 for 150 pcs crates.",
    createdBy: "Ayush Rajput (Owner)",
    timestamp: `${today}T10:30:00.000Z`,
  },
  {
    id: "int-102",
    clientId: "party-arihant",
    type: "call",
    text: "Called purchase manager regarding pending overdue invoice of ₹38,940. Promised payment by Friday.",
    createdBy: "Ayush Rajput (Owner)",
    timestamp: `${addDays(-3)}T15:20:00.000Z`,
  },
  {
    id: "int-103",
    clientId: "party-marwar-plastics",
    type: "visit",
    text: "Met proprietor Mr. Sharma in Kota. Discussed quarterly crate requirements.",
    createdBy: "Ayush Rajput (Owner)",
    timestamp: `${addDays(-10)}T11:00:00.000Z`,
  },
];

export const initialFollowUps: ClientFollowUp[] = [
  {
    id: "fu-201",
    clientId: "party-arihant",
    dueDate: today,
    reason: "Payment follow-up for overdue invoice INV-26-1002 (₹38,940 pending)",
    done: false,
    createdAt: `${addDays(-3)}T15:20:00.000Z`,
    autoSuggested: true,
  },
  {
    id: "fu-202",
    clientId: "party-marwar-plastics",
    dueDate: today,
    reason: "Send quotation and catalog for 20L Storage Crates",
    done: false,
    createdAt: `${addDays(-2)}T09:00:00.000Z`,
  },
];

export const initialInvoices: Invoice[] = [
  {
    id: "inv-26-101",
    partyId: "party-jaipur-mart",
    invoiceNumber: "INV-26-1001",
    items: [{ productId: "p-crate", quantity: 150, rate: 320, gstRate: 18 }],
    subtotal: 48000,
    gstAmount: 8640,
    total: 56640,
    status: "sent",
    dueDate: addDays(10),
    createdAt: `${today}T10:15:00.000Z`,
  },
  {
    id: "inv-26-102",
    partyId: "party-arihant",
    invoiceNumber: "INV-26-1002",
    items: [{ productId: "p-tray", quantity: 300, rate: 110, gstRate: 18 }],
    subtotal: 33000,
    gstAmount: 5940,
    total: 38940,
    status: "overdue",
    dueDate: addDays(-70),
    createdAt: `${addDays(-70)}T14:30:00.000Z`,
  },
];

export const initialLedgerEntries: LedgerEntry[] = [
  {
    id: "le-1",
    partyId: "party-jaipur-mart",
    invoiceId: "inv-26-101",
    amount: 56640,
    type: "debit",
    date: today,
    note: "GST Tax Invoice INV-26-1001 (150 pcs Crate)",
  },
  {
    id: "le-2",
    partyId: "party-arihant",
    invoiceId: "inv-26-102",
    amount: 38940,
    type: "debit",
    date: addDays(-70),
    note: "GST Tax Invoice INV-26-1002 (300 pcs Tray)",
  },
];

export const initialOrders: Order[] = [
  {
    id: "ord-801",
    orderNumber: "PO-CL-801",
    partyId: "party-jaipur-mart",
    invoiceId: "inv-26-101",
    items: [{ productId: "p-crate", quantity: 150, rate: 320, gstRate: 18 }],
    status: "dispatched",
    createdAt: `${today}T10:20:00.000Z`,
  },
  {
    id: "ord-802",
    orderNumber: "PO-CL-802",
    partyId: "party-arihant",
    invoiceId: "inv-26-102",
    items: [{ productId: "p-tray", quantity: 300, rate: 110, gstRate: 18 }],
    status: "in_transit",
    createdAt: `${addDays(-70)}T15:00:00.000Z`,
  },
];

export const initialDispatches: Dispatch[] = [
  {
    id: "disp-01",
    orderId: "ord-801",
    orderNumber: "PO-CL-801",
    partyName: "Jaipur Mega Mart & Distribution Ltd",
    transportProvider: "Porter Express Logistics",
    trackingId: "PTR-882193",
    vehicleType: "Tata 407 (14 Ft Open)",
    cost: 1200,
    status: "dispatched",
    createdAt: `${today}T12:00:00.000Z`,
  },
  {
    id: "disp-02",
    orderId: "ord-802",
    orderNumber: "PO-CL-802",
    partyName: "Arihant Industrial Supplies Corp",
    transportProvider: "VRL Logistics Transport",
    trackingId: "VRL-JOD-9921",
    vehicleType: "Mahindra Bolero Maxi Truck",
    cost: 1850,
    status: "in_transit",
    createdAt: `${addDays(-69)}T09:30:00.000Z`,
  },
];

export const initialNotices: PlantNotice[] = [
  {
    id: "not-01",
    title: "Preventive Maintenance Schedule - Machine #01 (L&T 250T)",
    content: "Hydraulic oil change and cooling tower descaling scheduled this Sunday morning. Plant power shutdown for 3 hours.",
    targetShift: "Maintenance Team",
    priority: "Urgent",
    date: today,
    issuedBy: "Plant Operations Head",
  },
  {
    id: "not-02",
    title: "Quality Standard Alert: Color Tone Consistency",
    content: "Strictly adhere to 1.8% masterbatch ratio for 20L crates to maintain export-grade blue color consistency.",
    targetShift: "All Shifts",
    priority: "High",
    date: today,
    issuedBy: "Quality Assurance Manager",
  },
];

export const initialExpenses: Expense[] = [
  {
    id: "exp-01",
    factoryId: "factory-jaipur-01",
    category: "rent",
    amount: 45000,
    paidTo: "Sitapura Industrial Estate RIICO",
    expenseDate: `${today.slice(0, 7)}-01`,
    note: "Plant Shed #1 Monthly Lease Rent",
    createdBy: "Ayush Rajput (Owner)",
    createdAt: `${today.slice(0, 7)}-01T09:00:00.000Z`,
  },
  {
    id: "exp-02",
    factoryId: "factory-jaipur-01",
    category: "electricity",
    amount: 62500,
    paidTo: "JVVNL Jaipur Vidyut Vitran Nigam",
    expenseDate: `${today.slice(0, 7)}-05`,
    note: "3-Phase Industrial HT Connection Power Bill",
    createdBy: "Ayush Rajput (Owner)",
    createdAt: `${today.slice(0, 7)}-05T11:30:00.000Z`,
  },
  {
    id: "exp-03",
    factoryId: "factory-jaipur-01",
    category: "maintenance",
    amount: 14800,
    paidTo: "Shree Ram Hydraulic Works",
    expenseDate: `${today.slice(0, 7)}-08`,
    note: "Machine #02 Hydraulic Seal Replacement & Filter Service",
    createdBy: "Ramesh Sharma (Supervisor)",
    createdAt: `${today.slice(0, 7)}-08T14:15:00.000Z`,
  },
  {
    id: "exp-04",
    factoryId: "factory-jaipur-01",
    category: "raw_material",
    amount: 125000,
    paidTo: "Reliance Polymers Ltd",
    expenseDate: `${today.slice(0, 7)}-10`,
    note: "5 Metric Tons HDPE Injection Grade Granules (Lot #HP-99)",
    createdBy: "Ayush Rajput (Owner)",
    createdAt: `${today.slice(0, 7)}-10T16:00:00.000Z`,
  },
  {
    id: "exp-05",
    factoryId: "factory-jaipur-01",
    category: "salary",
    amount: 85000,
    paidTo: "Floor Workers & Shift Operators",
    expenseDate: `${today.slice(0, 7)}-07`,
    note: "Shift 1 & Shift 2 Machine Operators Wage Disbursement",
    createdBy: "Ayush Rajput (Owner)",
    createdAt: `${today.slice(0, 7)}-07T10:00:00.000Z`,
  },
  {
    id: "exp-06",
    factoryId: "factory-jaipur-01",
    category: "other",
    amount: 4200,
    paidTo: "Jaipur Packaging & Adhesive Tape Mart",
    expenseDate: `${today.slice(0, 7)}-12`,
    note: "BOPP Packing Tape, Corrugated Rolls, and Stretch Film",
    createdBy: "Store Head",
    createdAt: `${today.slice(0, 7)}-12T13:45:00.000Z`,
  },
];

